[workspace]

members = [
    # Public workspace crates
    #"gdlisp",
    "gdextension-api",
    "gdextension-serde",
    "gdlisp-core",
    "gdlisp-parser",
    "gdlisp-util",

    # Godot test crates
    "tests/gdextension-serde-tests/rust",
]