name: Clippy Style Checker

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style-checker:

    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2
    - name: Install Clippy
      run: |
        rustup update
        rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy --verbose
