name: "Ubuntu 20.04 (Godot v3.3.3)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-suite:

    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2
    - name: Install Godot
      run: |
        mkdir godot-build
        cd godot-build
        wget https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_linux_headless.64.zip
        unzip Godot_v3.3.3-stable_linux_headless.64.zip
        ln -s Godot_v3.3.3-stable_linux_headless.64 godot
        ls -l
        cd ..
    - name: Build
      run: rake build[--verbose]
    - name: Run Standard Test Suite
      run: |
        PATH="$PWD/godot-build/:$PATH"
        echo "$PATH"
        rake test[--verbose]
    - name: Run Full Test Suite
      run: |
        PATH="$PWD/godot-build/:$PATH"
        echo "$PATH"
        rake 'test[--verbose,--,--ignored]'
