name: "Ubuntu 20.04 (Godot v3.5 Minimal)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-suite:

    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2
    - name: Install Godot
      run: |
        mkdir godot-build
        cd godot-build
        wget https://www.dropbox.com/s/9zi0ij7cqetaw34/godot_server.x11.opt.tools.64.zip?dl=1 -O godot_server.x11.opt.tools.64.zip
        unzip godot_server.x11.opt.tools.64.zip
        ln -s godot_server.x11.opt.tools.64 godot
        ls -l
        cd ..
    - name: Build
      run: |
        PATH="$PWD/godot-build/:$PATH"
        echo "$PATH"
        rake build[--verbose]
    - name: Run Standard Test Suite
      run: |
        PATH="$PWD/godot-build/:$PATH"
        echo "$PATH"
        rake 'test[--verbose]'
